# roles/recon_box/handlers/main.yml

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
