# vault.yml — encrypt before committing: ansible-vault encrypt group_vars/vault.yml

vault_authelia_jwt_secret: mTad6V4hP79UtTjHpCLlySVqGNb1fjWJpGsyty71n1pg7HQdfaug3tfG3NSKwwk
vault_authelia_session_secret: JhQ3RNINZAuaaytulRwM6yFfYtwoeGTmVdh0eLNNICcdlT7ldHufxm6bq4BRS
vault_authelia_storage_encryption_key: bb8da1OdYCASMUIpYTbRXZrMFkUeTdO1BHPHUv3jtvrASZSdzICs2ne7KEn5qVfY
vault_umami_postgres_password: Jv6lAqd7Kibvkccn1IknlmMquXREM8W
vault_umami_app_secret: 6Uu3JJUCJUARYcTMuaWLTkgoCsYbVXUp
